name: Chocolate Workflow
on:
  push:
    branches:
      - main

env:
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-MPL-2-1-chocolatine-ambre.cornejo.git"
  EXECUTABLES: "my_navy"

jobs:
  compil:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    timeout-minutes: 2
    needs: [coding_style]

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: push
        run: make

      - name: check_compil
        run: |
          for file in ${{env.EXECUTABLES}}; do
            if [ ! -f $file ]; then
              echo "Compilation KO"
              exit 1
            fi
          echo "Compilation OK"
          done
      
      - name: clean
        run: make clean

  coding_style:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container: ghcr.io/epitech/coding-style-checker:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: coding_style
        run: make fclean

      - name: check_coding_style
        run: check.sh . /tmp

      - name: cat codi
        run: |
          NB_ERROR=$(cat /tmp/coding-style-reports.log | wc -l)
          if [ $NB_ERROR -gt 0 ]; then
            echo "Coding style KO"
            exit 1
          fi

  unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container: epitechcontent/epitest-docker:latest
    needs: [compil]

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: unit_tests
        run: make tests_run

  mirroring:
    runs-on: ubuntu-latest
    needs:  run_tests
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
